---
language: ruby
notifications:
  email:
    recipients:
      - drbrain@segment7.net
      - shugo@ruby-lang.org
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
before_install: gem install bundler -v '<2'
script: rake compile
